DYNAMODB_ATTENDANCE_TABLE_NAME = "swiftAttendance"
DYNAMODB_STUDENT_TABLE_NAME = "swiftAttendStudents"
DYNAMODB_LECTURER_TABLE_NAME = "swiftAttendLecturers"
DYNAMODB_CLASSES_TABLE_NAME = "swiftAttendClasses"
REKOGNITION_COLLECTION_NAME = "swiftAttend"
COGNITO_CLIENT_ID = '66soki1i4q3q8ttrera7f6318v'
S3_BUCKET_NAME = 'swift-attend-faces'